# IN LOGGER WE NEED TO CHANGE THAT NOW WE HAVE DIFFERENT LR FOR EACH MODEL-S PARAMETERS
model_name: GRAPHDOCT5VQA_ADDWORDS
# save_dir: /data2/users/rriccio/save_vt5_gdoc_weigh_t5/
save_dir: /data2/users/rriccio/save_GRAPHDOCT5VQA_ADDWORDS/
model_weights: t5-base

max_source_length: 512
device: cuda
data_parallel: True

training_parameters:
  lr_projection: 2e-4
  lr_t5_decoder: 5e-5
  lr_graphdoc: 5e-5 
  # lr_t5: 5e-5
  lr: 2e-5  # 2e-4
  batch_size: 1
  train_epochs: 10
  warmup_iterations: 0

visual_module:
  model: 'dit'  # 'vit' / 'dit'
  finetune: false
  model_weights: 'microsoft/dit-base-finetuned-rvlcdip'  # 'google/vit-base-patch16-224-in21k' / 'microsoft/dit-base-finetuned-rvlcdip'


graphdoc_ckpt: /data2/users/rriccio/pretrained_model/graphdoc
sentence_bert_path: /data2/users/rriccio/pretrained_model/sentence-bert
t5_name: t5-base # Matches model_weights for T5 tokenizer/model consistency
add_projection: True