
model_name: VT5_GDOC_PROJECT_GDOC
# save_dir: /data2/users/rriccio/save_vt5_gdoc_weigh_t5/
save_dir: /data2/users/rriccio/save_projectgdoc_vt5_gdoc_weigh_t5/
model_weights: t5-base

max_source_length: 512
device: cuda
data_parallel: False

training_parameters:
  lr: 2e-4  # 2e-4
  batch_size: 2
  train_epochs: 10
  warmup_iterations: 1000

visual_module:
  model: 'dit'  # 'vit' / 'dit'
  finetune: false
  model_weights: 'microsoft/dit-base-finetuned-rvlcdip'  # 'google/vit-base-patch16-224-in21k' / 'microsoft/dit-base-finetuned-rvlcdip'


