dataset_name: SP_DocVQA_GRAPHDOC
# Use the QAS folder as the location for the QA JSON file.
imdb_dir: /data2/users/rriccio/spdocvqa_qas
images_dir: /data2/users/rriccio/spdocvqa_images

ocr_dir: /data2/users/rriccio/spdocvqa_ocr
ocr_graphdoc_dir: /data2/users/rriccio/easyocr_spdocvqa  # This contains the OCR JSON files for the SP DocVQA dataset using EASYOCR